# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecb86307600657f4031868f4a11a52e71dad7f59616d54cfb732f747e710e091cc9ff3c2e4b814ca7d70fc22aef5749317411ae3f80dbc4a434028e6e637b4b

test:
  secret_key_base: 655d2a34454e8b4ca1464dd169707e65d9e290483893593244d3a5b4c2cf5d267de128eef52cc7bc32344a9cada38c3abd2ff9fcf06755431029e0cfb5fcd65a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
